### ISSUE TITLE
Service start times out

### ISSUE THREAD

**Issue by codl** [cdown/psi-notify#23]
On Arch, using the AUR package and the included service file, it seems psi-notify is not successfully notifying systemd that it is ready, and as a result it keeps getting restarted every ~90 seconds.

```
$ journald --user-unit psi-notify --since '3m ago'
Nov 20 02:31:07 peanut.codl.fr systemd[1188]: Starting psi-notify.service...
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]: INFO: Using system-global resource pressures.
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]: INFO: Config:
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]:       Log pressures: false
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]:       Update interval: 5s
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]:       Thresholds:
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]:         - CPU avg10 some: 50.00
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]:         - Memory avg10 some: 10.00
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]:         - I/O avg10 full: 15.00
Nov 20 02:31:07 peanut.codl.fr psi-notify[5624]: INFO: Pressure monitoring started.
Nov 20 02:32:38 peanut.codl.fr systemd[1188]: psi-notify.service: start operation timed out. Terminating.
Nov 20 02:32:38 peanut.codl.fr psi-notify[5624]: INFO: Terminating after 19 intervals elapsed.
Nov 20 02:32:38 peanut.codl.fr systemd[1188]: psi-notify.service: Failed with result 'timeout'.
Nov 20 02:32:38 peanut.codl.fr systemd[1188]: Failed to start psi-notify.service.
Nov 20 02:32:38 peanut.codl.fr systemd[1188]: psi-notify.service: Scheduled restart job, restart counter is at 33.
Nov 20 02:32:38 peanut.codl.fr systemd[1188]: Stopped psi-notify.service.
Nov 20 02:32:38 peanut.codl.fr systemd[1188]: Starting psi-notify.service...
Nov 20 02:32:38 peanut.codl.fr psi-notify[5641]: INFO: Using system-global resource pressures.
etc...
```

Between restarts it seems to work fine, I can cause pressure and get a notification.

Is there something I am missing?

**Comment by cdown** [comment]
Hi! It sounds like your unit is `Type=notify`, but you don't have sd_notify support compiled in.

1. What does `ldd "$(command -v psi-notify)"` show?
2. Does `strace` show notify-like write activity?

**Comment by codl** [comment]
Indeed, it looks like I didn't have `sd_notify` support. I build AUR packages in a chroot, and because `systemd-libs` was not an explicit dependency it was not present at build time.

Once I edited the `PKGBUILD` to include `systemd-libs` as a dependency, it ran fine and notified fine.

**Comment by cdown** [comment]
systemd (which depends on `systemd-libs`) is part of `base`, which isn't needed to be explicitly mentioned in PKGBUILDs. You should probably install it :-)

**Comment by codl** [comment]
No, I think `systemd-libs` or `systemd` should be explicitly required in the `PKGBUILD`.

While `base` is required at runtime, only the contents of `base-devel` are required at build time, and it is a common practice to [build packages in a clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot) which only has the contents of `base-devel` preinstalled. Some AUR helpers do this automatically.

Additionally, the [Arch package guidelines](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_dependencies) say to list all direct library dependencies. You can find in the official repositories dozens of packages that have some combination of `systemd` and/or `systemd-libs` in their deps and/or makedeps.

Let me know if I should move this discussion to the AUR package comments.

**Comment by cdown** [comment]
Oh, you're correct. I was under the incorrect impression that both base and base-devel were required. I'll add in systemd-libs then -- thanks :-)

**Comment by cdown** [comment]
psi-notify 1.2.1-2 published to AUR. Thanks!

**Comment by codl** [comment]
Hmm it looks like it is still not building with notify support, looks like while the libs are in `systemd-libs`, the pkg-config files are in `systemd` so it needs to be there at build time at least, my bad for saying it worked with `systemd-libs` earlier
