### ISSUE TITLE
Create debian package

### ISSUE THREAD

**Issue by disdi** [cdown/psi-notify#25]
This is to request Debian package for psi-notify.

If this is not planned in Roadmap, I am willing to contribute this feature.

Though installing on Ubuntu works with rpm package via alien as shown below:

`disdi@disdi-Precision-5540:~/Downloads$ sudo alien -i  psi-notify-1.2.1-5.fc36.x86_64.rpm `
`
Preparing to unpack psi-notify_1.2.1-6_amd64.deb ...
Unpacking psi-notify (1.2.1-6) ...
Setting up psi-notify (1.2.1-6) ...
`

**Comment by cdown** [comment]
I believe @michel-slm is already looking at this. From my side, I don't run Debian, so it's up to Debian users to contribute and maintain the packaging there :-)

**Comment by michel-slm** [comment]
It's being reviewed right now! Almost ready to get uploaded. https://mentors.debian.net/package/psi-notify/

**Comment by pabs3** [comment]
I've uploaded the package by @michel-slm to Debian, next it will get [reviewed](https://ftp-master.debian.org/new.html) by the Debian archive admin team.

**Comment by pabs3** [comment]
The Debian archive admin team have accepted the psi-notify package. @michel-slm will maintain the package and I'll sponsor package updates. So I think this issue can be closed now @disdi @cdown. I'll be happy to sponsor a backport for use on Debian stable once the package reaches Debian testing (bookworm).

https://tracker.debian.org/pkg/psi-notify
